package expo.modules.smsreader

import android.app.PendingIntent
import android.content.Context
import android.content.Intent

/**
 * The one deep-link channel shared by the launcher shortcut, the Quick Settings tile and
 * all four home-screen widgets. MainActivity is generated by Expo prebuild (and
 * apps/raqm/android is gitignored), so we cannot subclass or edit it — instead we put
 * extras on its ordinary launch intent and let JS drain them from
 * SmsReaderModule.consumeLaunchDeepLink() on mount and on every foreground.
 * ReactActivity.onNewIntent() calls setIntent(), so a warm launch updates
 * activity.intent before JS ever reads it.
 */
object QuickAdd {
  const val EXTRA_OPEN_QUICK_ADD = "openQuickAdd"
  const val EXTRA_OPEN_TRANSACTION = "openTransaction"

  /**
   * The launcher-activity intent carrying the deep-link extras. Glance's `actionStartActivity`
   * takes a raw Intent (it has no PendingIntent overload), so widgets use this directly while
   * the shortcut/tile wrap it below — one place builds the intent either way.
   * Returns null if the launcher intent can't be resolved (never throws).
   */
  fun mainActivityIntent(
    context: Context,
    quickAdd: Boolean,
    transactionId: Int? = null,
  ): Intent? {
    val intent = try {
      context.packageManager.getLaunchIntentForPackage(context.packageName)
    } catch (e: Exception) {
      null
    } ?: return null

    intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_SINGLE_TOP)
    if (quickAdd) intent.putExtra(EXTRA_OPEN_QUICK_ADD, true)
    if (transactionId != null) intent.putExtra(EXTRA_OPEN_TRANSACTION, transactionId)
    return intent
  }

  /**
   * A PendingIntent that (re)launches the app's own launcher activity carrying the
   * deep-link extras. `requestCode` must be distinct per caller/row, otherwise Android
   * reuses one PendingIntent and every widget row would open the same transaction.
   * Returns null if the launcher intent can't be resolved (never throws).
   */
  fun mainActivityPendingIntent(
    context: Context,
    requestCode: Int,
    quickAdd: Boolean,
    transactionId: Int? = null,
  ): PendingIntent? {
    val intent = mainActivityIntent(context, quickAdd, transactionId) ?: return null

    return try {
      PendingIntent.getActivity(
        context,
        requestCode,
        intent,
        PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE,
      )
    } catch (e: Exception) {
      null
    }
  }
}
