#!/usr/bin/env bash
# PreToolUse(Edit|Write): block edits under apps/raqm/android/. CLAUDE.md:
# that directory is gitignored and regenerated by `expo prebuild` — native
# changes only survive inside apps/raqm/modules/sms-reader/.
set -uo pipefail

input="$(cat)"
file_path="$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty')"

[[ -z "$file_path" ]] && exit 0

case "$file_path" in
  *apps/raqm/android/*)
    echo "Blocked: $file_path is under apps/raqm/android/, which is gitignored and regenerated by 'expo prebuild'. Edits there are lost on next prebuild — make native changes in apps/raqm/modules/sms-reader/ instead." >&2
    exit 2
    ;;
esac

exit 0
