import UIKit

/// iOS mirror of QuickAdd.kt: the one deep-link channel for the Home Screen "Add Cash Spend"
/// Quick Action shortcut. AppDelegate is generated by Expo prebuild (apps/raqm/ios is
/// gitignored), so we cannot subclass it — instead SmsReaderAppDelegateSubscriber captures
/// the shortcut tap into `pending` here, and JS drains it via
/// SmsReaderModule.consumeLaunchDeepLink() on mount and on every foreground.
enum QuickAdd {
  static let shortcutType = "com.raqm.quickAddCash"
  static let voiceShortcutType = "com.raqm.quickAddVoice"

  struct Pending {
    var openQuickAdd: Bool
    var openTransaction: Int?
    var startVoice: Bool = false
  }

  /// Set by the AppDelegate subscriber when a shortcut is tapped (cold or warm launch),
  /// cleared by consumeLaunchDeepLink() the first time JS reads it.
  static var pending: Pending?

  /// Dynamic (not Info.plist-static) shortcut, so it needs no build-time plist entry —
  /// mirrors Android's ShortcutManagerCompat.pushDynamicShortcut, re-set on every launch.
  static func registerShortcut() {
    let cash = UIApplicationShortcutItem(
      type: shortcutType,
      localizedTitle: "Add Cash Spend",
      localizedSubtitle: nil,
      icon: UIApplicationShortcutIcon(systemImageName: "plus.circle")
    )
    let voice = UIApplicationShortcutItem(
      type: voiceShortcutType,
      localizedTitle: "Voice cash spend",
      localizedSubtitle: nil,
      icon: UIApplicationShortcutIcon(systemImageName: "mic.circle")
    )
    UIApplication.shared.shortcutItems = [cash, voice]
  }

  static func handle(_ item: UIApplicationShortcutItem) -> Bool {
    switch item.type {
    case shortcutType:
      pending = Pending(openQuickAdd: true, openTransaction: nil)
      return true
    case voiceShortcutType:
      pending = Pending(openQuickAdd: true, openTransaction: nil, startVoice: true)
      return true
    default:
      return false
    }
  }
}
